### ISSUE TITLE
要不用社交软件讨论这些问题

### ISSUE THREAD

**Issue by hm9245** [gaoe6661/anti-America-hegemony#14]
我tg在我主页，看你愿不愿意加

**Comment by gaoe6661** [comment]
说实话没必要吧，兄弟不要把这个当主业了啊，我们不是CIA，我们没工资拿啊。
有啥问题可以直接改，如果我觉得不行我可以直接还原备份，然后告诉你。

**Comment by hm9245** [comment]
> 说实话没必要吧，兄弟不要把这个当主业了啊，我们不是CIA，我们没工资拿啊。
> 有啥问题可以直接改，如果我觉得不行我可以直接还原备份，然后告诉你。

虽然没必要，但也有必要......我们就是一些社区贡献者而已，尽管我们没钱拿，我也要反对滥用行为，用聊天软件方便治理，懒得发一堆issues
当初因为这个垃圾[repo](https://github.com/cirosantilli/china-dictatorship)，所以我加入你，目的不仅反米果cia，还要把这些垃圾给清掉
**总之，管他有没有钱拿，清理垃圾仓库才是真正的有钱拿......**

**Comment by hm9245** [comment]
还有我没把这个当主业，只是单纯的反感这种行为罢了......

**Comment by gaoe6661** [comment]
...
也是也是，但是还是github上讨论吧，因为最近也比较忙，所以其它社交软件可能压根不看。。。

**Comment by hm9245** [comment]
> ...
> 也是也是，但是还是github上讨论吧，因为最近也比较忙，所以其它社交软件可能压根不看。。。

好吧
