### ISSUE TITLE
位更寄

### ISSUE THREAD

**Issue by hm9245** [gaoe6661/anti-America-hegemony#18]
![image](https://github.com/gaoe6661/anti-America-hegemony/assets/141204703/bb765cf8-2073-4373-a2d8-fcc7b88b4fcf)

**Comment by hm9245** [comment]
@gaoe6661 速来吃瓜

**Comment by gaoe6661** [comment]
没明白，寄了吗？

**Comment by hm9245** [comment]
意思是：这位更是重量级，简称（这）位更（是重量）级
________________________________
发件人: gaoe6661 ***@***.***>
发送时间: 2023年10月29日 0:57
收件人: gaoe6661/anti-America-hegemony ***@***.***>
抄送: haoming9245 ***@***.***>; Assign ***@***.***>
主题: Re: [gaoe6661/anti-America-hegemony] 位更寄 (Issue #18)


没明白，寄了吗？

―
