### ISSUE TITLE
反共的标签去了吧

### ISSUE THREAD

**Issue by hm9245** [gaoe6661/anti-America-hegemony#9]
怕有人以为我们在反串
![图片](https://github.com/gaoe6661/anti-America-hegemony/assets/141204703/03e39b6c-1d01-4a79-b22c-6c7e8f63a88b)

**Comment by gaoe6661** [comment]
ok，你看着改就行，加上主要是为了给他们一些小小的震撼，要不然那群撅醒青年被洗了就不好了（捂脸）

以后你看着改就行，如果我觉得不行我会再at你告诉下原因。
